# Generated by Django 4.2.5 on 2023-09-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMMantenimiento', '0002_trabajador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('fechaDeEntrega', models.DateField()),
                ('entregado', models.BooleanField()),
            ],
        ),
    ]
